### ISSUE TITLE
Fix java detection on Windows

### ISSUE THREAD

**Issue by ssbarnea** [jenkinsci/ssh-slaves-plugin#10]
currently the plugin fails to detect java presense on Windows machines. For example I do have a Windows 2008 Server with SSH enabled via SUA, Java 1.7 installed and available from the command line.

Still the plugin fails to detect java.

Running java from the ssh prompt works but if you try to use "which java" it will fail because java executable is not in PATH. 

Still the real location on the disk is on "/dev/fs/C/Program Files/Java/jre7/bin/java.exe"

The whole purpose of this is to improve the detection mechanism so it will not require manual work for installing the slaves.

**Comment by jglick** [comment]
Please use JIRA for issue reports.
