### ISSUE TITLE
Replace trilead with maybe bouncy castle

### ISSUE THREAD

**Issue by paladox** [jenkinsci/ssh-slaves-plugin#39]
Hi could trilead be replaced with maybe bouncy castle please as trilead is very old and is in secure and uses in secure keys whereas bouncy castle includes the newer keys and is more secure please.

See downstream report https://phabricator.wikimedia.org/T103351 please.

**Comment by paladox** [comment]
It would also need to be updated in https://github.com/jenkinsci/ssh-credentials-plugin

+ jenkins upstream updated ssh from 0.8 to 0.14.0 so they include the newer ssh keys.

**Comment by paladox** [comment]
Or use the core jenkins sshd as it is newer and comes with bouncy castle.

**Comment by oleg-nenashev** [comment]
Closing since it duplicates [JENKINS-33021](https://issues.jenkins-ci.org/browse/JENKINS-33021)
