### ISSUE TITLE
download slave.jar to docker instance failed by sftp

### ISSUE THREAD

**Issue by oulinbao** [jenkinsci/ssh-slaves-plugin#45]
I am using docker plugin of jenkins to deploy docker cloud. It's an amazing function.
After I made the slave docker image on the localhost, it's all work fine.
The docker instance could be created and download slave.jar to the instance and then execute the job.
But if the docker instance runs on a virtual machine of openstack, the slave.jar could not be download by sftp successfully. Because this is a constraint of openstack. To solve this problem, I have two methods:
1) use passive mode of sftp
2) use scp but not sftp 
Can any one supports this scenario?
Thanks a lot.

**Comment by oleg-nenashev** [comment]
Please raise the issue in Jenkins JIRA.
If SFTP connection fails, SCP will likely also fail, right?

**Comment by oulinbao** [comment]
Thanks to your reply.
I have modified the code, and use scp directly. It works fine.
Because scp will not open another connection between client and server.

Yours,
OuLinbao


At 2017-03-10 14:55:58, "Oleg Nenashev" <notifications@github.com> wrote:


Please raise the issue in Jenkins JIRA.
If SFTP connection fails, SCP will likely also fail, right?
