### ISSUE TITLE
Switch from using trilead-ssh2 to an alternative one please

### ISSUE THREAD

**Issue by paladox** [jenkinsci/ssh-slaves-plugin#46]
Hi, trilead-ssh2 is out of date and insecure. Could we please switch to an alternative like bouncy castle or apache sshd (mina) please?

https://mina.apache.org/sshd-project/embedding_ssh.html

trilead-ssh2 doesn't allow you to use the latest ssh protocol and doesn't allow you to use sha2 which wikimedia needs for it's slaves.

cc @olivergondza

**Comment by oleg-nenashev** [comment]
Yes, this is a known problem and a high technical debt in Jenkins. FTR https://issues.jenkins-ci.org/browse/JENKINS-33021

**Comment by paladox** [comment]
This should presumably be fixed with https://github.com/jenkinsci/trilead-ssh2/pull/9 though we should still switch as trilead-ssh2 is unmaintained :)

**Comment by paladox** [comment]
We doing need to switch now. a new release of trilead-ssh2 has been done. :)
