### ISSUE TITLE
Failed known_hosts verification for SSH agent

### ISSUE THREAD

**Issue by wl2776** [jenkinsci/ssh-slaves-plugin#48]
SSH agent isn't launched after the latest update, complaining about missing records in the known hosts file. 

Nevertheless, the records do exist.

     [03/21/17 11:40:34] [SSH] Opening SSH connection to xxx.xxx.xxx.xxx:22
     [03/21/17 11:40:34] [SSH] WARNING: No entry currently exists in the Known Hosts file for this host.      Connections will be denied until this new host and its associated key is added to the Known Hosts file.
     Key exchange was not finished, connection is closed.
     java.io.IOException: There was a problem while connecting to xxx.xxx.xxx.xxx:22
	at com.trilead.ssh2.Connection.connect(Connection.java:818)
	at com.trilead.ssh2.Connection.connect(Connection.java:687)
	at com.trilead.ssh2.Connection.connect(Connection.java:601)
	at hudson.plugins.sshslaves.SSHLauncher.openConnection(SSHLauncher.java:1265)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:790)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:785)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
     Caused by: java.io.IOException: Key exchange was not finished, connection is closed.
	at com.trilead.ssh2.transport.KexManager.getOrWaitForConnectionInfo(KexManager.java:93)
	at com.trilead.ssh2.transport.TransportManager.getConnectionInfo(TransportManager.java:230)
	at com.trilead.ssh2.Connection.connect(Connection.java:770)
	... 9 more
     Caused by: java.io.IOException: The server hostkey was not accepted by the verifier callback
	at com.trilead.ssh2.transport.KexManager.handleMessage(KexManager.java:591)
	at com.trilead.ssh2.transport.TransportManager.receiveLoop(TransportManager.java:777)
	at com.trilead.ssh2.transport.TransportManager$1.run(TransportManager.java:489)
	... 1 more
     [03/21/17 11:40:34] Launch failed - cleaning up connection
     [03/21/17 11:40:34] [SSH] Connection closed.

However, when trying to connect manually with ssh, everything is fine, it reports that it has found the host in known_hosts:

    $ sudo -u jenkins -g jenkins ssh -v jenkins@xxx.xxx.xxx.xxx
    [sudo] password:
    OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
    debug1: Reading configuration data /etc/ssh/ssh_config
    debug1: /etc/ssh/ssh_config line 19: Applying options for *
    debug1: Connecting to xxx.xxx.xxx.xxx [xxx.xxx.xxx.xxx] port 22.
    debug1: Connection established.
    debug1: identity file /var/lib/jenkins/.ssh/id_rsa type 1
    debug1: identity file /var/lib/jenkins/.ssh/id_rsa-cert type -1
    debug1: identity file /var/lib/jenkins/.ssh/id_dsa type -1
    debug1: identity file /var/lib/jenkins/.ssh/id_dsa-cert type -1
    debug1: identity file /var/lib/jenkins/.ssh/id_ecdsa type -1
    debug1: identity file /var/lib/jenkins/.ssh/id_ecdsa-cert type -1
    debug1: identity file /var/lib/jenkins/.ssh/id_ed25519 type -1
    debug1: identity file /var/lib/jenkins/.ssh/id_ed25519-cert type -1
    debug1: Enabling compatibility mode for protocol 2.0
    debug1: Local version string SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
    debug1: Remote protocol version 2.0, remote software version OpenSSH_7.2p2 Ubuntu-4ubuntu2.1
    debug1: match: OpenSSH_7.2p2 Ubuntu-4ubuntu2.1 pat OpenSSH* compat 0x04000000
    debug1: SSH2_MSG_KEXINIT sent
    debug1: SSH2_MSG_KEXINIT received
    debug1: kex: server->client aes128-ctr hmac-sha1-etm@openssh.com none
    debug1: kex: client->server aes128-ctr hmac-sha1-etm@openssh.com none
    debug1: sending SSH2_MSG_KEX_ECDH_INIT
    debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
    debug1: Server host key: ECDSA xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx
    debug1: Host 'xxx.xxx.xxx.xxx.xxx' is known and matches the ECDSA host key.
    debug1: Found key in /var/lib/jenkins/.ssh/known_hosts:2
    debug1: ssh_ecdsa_verify: signature correct
    debug1: SSH2_MSG_NEWKEYS sent
    debug1: expecting SSH2_MSG_NEWKEYS
    debug1: SSH2_MSG_NEWKEYS received
    debug1: SSH2_MSG_SERVICE_REQUEST sent
    debug1: SSH2_MSG_SERVICE_ACCEPT received
    debug1: Authentications that can continue: publickey,password
    debug1: Next authentication method: publickey
    debug1: Offering RSA public key: /var/lib/jenkins/.ssh/id_rsa
    debug1: Server accepts key: pkalg ssh-rsa blen 279
    debug1: key_parse_private2: missing begin marker
    debug1: read PEM private key done: type RSA
    debug1: Authentication succeeded (publickey).
    Authenticated to xxx.xxxx.xxx.xxx ([xxx.xxx.xxx.xxx]:22).
    debug1: channel 0: new [client-session]
    debug1: Requesting no-more-sessions@openssh.com
    debug1: Entering interactive session.
    debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
    debug1: Sending environment.
    Welcome to Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-67-generic x86_64)

Versions: 

Jenkins:  2.51
SSH Agent Plugin: 1.14
SSH Credentials plugin: 1.13
SSH Slaves Plugin : 1.15

**Comment by wl2776** [comment]
Additional logs from Jenkins system log:

    Mar 21, 2017 12:06:08 PM FINER com.trilead.ssh2.transport.KexManager
    kex_algo=diffie-hellman-group14-sha1
    Mar 21, 2017 12:06:08 PM FINER com.trilead.ssh2.transport.KexManager
    server_host_key_algo=ssh-rsa
    Mar 21, 2017 12:06:08 PM FINER com.trilead.ssh2.transport.KexManager
    enc_algo_client_to_server=aes256-ctr
    Mar 21, 2017 12:06:08 PM FINER com.trilead.ssh2.transport.KexManager
    enc_algo_server_to_client=aes256-ctr
    Mar 21, 2017 12:06:08 PM FINER com.trilead.ssh2.transport.KexManager
    mac_algo_client_to_server=hmac-sha1
    Mar 21, 2017 12:06:08 PM FINER com.trilead.ssh2.transport.KexManager
    mac_algo_server_to_client=hmac-sha1
    Mar 21, 2017 12:06:08 PM FINER com.trilead.ssh2.transport.KexManager
    comp_algo_client_to_server=none
    Mar 21, 2017 12:06:08 PM FINER com.trilead.ssh2.transport.KexManager
    comp_algo_server_to_client=none
    Mar 21, 2017 12:06:08 PM FINE com.trilead.ssh2.transport.TransportManager
    Receive thread: error in receiveLoop
    java.io.IOException: The server hostkey was not accepted by the verifier callback
            at com.trilead.ssh2.transport.KexManager.handleMessage(KexManager.java:591)
            at com.trilead.ssh2.transport.TransportManager.receiveLoop(TransportManager.java:777)
            at com.trilead.ssh2.transport.TransportManager$1.run(TransportManager.java:489)
            at java.lang.Thread.run(Thread.java:745)

    Mar 21, 2017 12:06:08 PM FINER com.trilead.ssh2.transport.TransportManager
    Receive thread: back from receiveLoop
    Mar 21, 2017 12:06:10 PM FINER com.trilead.ssh2.transport.KexManager
    kex_algo=diffie-hellman-group14-sha1
    Mar 21, 2017 12:06:10 PM FINER com.trilead.ssh2.transport.KexManager
    server_host_key_algo=ssh-rsa
    Mar 21, 2017 12:06:10 PM FINER com.trilead.ssh2.transport.KexManager
    enc_algo_client_to_server=aes256-ctr
    Mar 21, 2017 12:06:10 PM FINER com.trilead.ssh2.transport.KexManager
    enc_algo_server_to_client=aes256-ctr
    Mar 21, 2017 12:06:10 PM FINER com.trilead.ssh2.transport.KexManager
    mac_algo_client_to_server=hmac-sha1
    Mar 21, 2017 12:06:10 PM FINER com.trilead.ssh2.transport.KexManager
    mac_algo_server_to_client=hmac-sha1
    Mar 21, 2017 12:06:10 PM FINER com.trilead.ssh2.transport.KexManager
    comp_algo_client_to_server=none
    Mar 21, 2017 12:06:10 PM FINER com.trilead.ssh2.transport.KexManager
    comp_algo_server_to_client=none
    Mar 21, 2017 12:06:10 PM FINE com.trilead.ssh2.transport.TransportManager
    Receive thread: error in receiveLoop
    java.io.IOException: The server hostkey was not accepted by the verifier callback
            at com.trilead.ssh2.transport.KexManager.handleMessage(KexManager.java:591)
            at com.trilead.ssh2.transport.TransportManager.receiveLoop(TransportManager.java:777)
            at com.trilead.ssh2.transport.TransportManager$1.run(TransportManager.java:489)
            at java.lang.Thread.run(Thread.java:745)

    Mar 21, 2017 12:06:10 PM FINER com.trilead.ssh2.transport.TransportManager
    Receive thread: back from receiveLoop

**Comment by mc1arke** [comment]
Please use Jira for reporting problems so we keep all issues together.

Can you check the known hosts file in $user.home/.ssh/known_hosts to check the hostname matches the one Jenkins is configured with?

**Comment by wl2776** [comment]
Ok, I will submit this to Jira, if we will find that this is an issue indeed.

From ssh debug output: 
    
    debug1: Found key in /var/lib/jenkins/.ssh/known_hosts:2

The second line of known_hosts contains some hashes, probably in BASE64, delimited by "|"

**Comment by mc1arke** [comment]
I wonder if Trilead's known hosts verifier doesn't deal with hashed hostnames. I'll have a look.

**Comment by wl2776** [comment]
Something like the following:
    
    |1|DAg  ...   o... 1ll9wI=| ...  ....  tIrM= ecdsa-sha2-nistp256 xxxxxx..... bmlzdHAyNTYAAAAIbm.................PS...............xxxxxxxxxxxoKEHF3Vr0q685jI2+6vWjvAAG4lz5Ckujy9k=

**Comment by mc1arke** [comment]
Yes, that's a hashed hostname which is probably what's causing the issue. The Trilead source does looks like it's supposed to be-able to handle hashed hostnames so I'll need to try and create some test cases that proves this functionality. Could you raise a Jira ticket to cover this (I'm going to close this issue now) and I'll try and replicate and investigate this issue based on any information you can provide.

**Comment by wl2776** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-42959
