### ISSUE TITLE
No license in pom.xml (or anywhere else visible from the repo page)

### ISSUE THREAD

**Issue by jwbowen** [jenkinsci/ssh-slaves-plugin#60]
My CI team would like to be able to use this plugin, but we need to see a license in order to seek approval from our legal team.

**Comment by jwbowen** [comment]
I see that the MIT license is listed at the top of each source file.

A license in the pom.xml or LICENSE.txt would be very helpful for organizations that need to seek legal approval before using a piece of software.

**Comment by oleg-nenashev** [comment]
Please feel free to submit a pull request or to create a JIRA issue for it.

**Comment by jwbowen** [comment]
Created PR #64 to add a LICENSE.txt

**Comment by jwbowen** [comment]
PR #64 merged, so there is now a prominent license in the repo.

Closing.
