### ISSUE TITLE
Allow retrying forever?

### ISSUE THREAD

**Issue by nh2** [jenkinsci/ssh-slaves-plugin#62]
https://github.com/jenkinsci/ssh-slaves-plugin/pull/19 introduced retries for connecting to the agent.

Could it be changed such such that it can be configured to retry forever, as opposed some maximum number of times?

That also seems like a good default to me.

Thanks!

**Comment by oleg-nenashev** [comment]
Please raise a JIRA ticket for it

**Comment by nh2** [comment]
OK: https://issues.jenkins-ci.org/browse/JENKINS-44845

**Comment by oleg-nenashev** [comment]
Thanks!
@olivergondza @stephenc @jglick Do we want to keep GitHub issues for tyhis plugin? If no, I can disable them

**Comment by nh2** [comment]
If you want a third party opinion: Having Github issues lowered the contribution threshold for me.

**Comment by olivergondza** [comment]
Not that there is anybody who would go through the issues reported proactively. I have the GH issues on for openstack plugin and I am fine with that from maintainer POW.

So if my opinion have any value here, I ok to let it open.

**Comment by oleg-nenashev** [comment]
OK, let's keep it open

**Comment by olivergondza** [comment]
But since we already have the JIRA, I am moving the discussion there.
